"""Constraint programming solvers for master schedule generation."""

from lab_scheduler.solver.cpsat_fill import (
    CpSatFillResult,
    PORTAGE_MAX_CONSECUTIVE_NIGHTS,
    PORTAGE_MAX_CONSECUTIVE_WORK_DAYS,
    FULLTIME_ACTIVE_WEEKENDS_REQUIRED,
    PARTTIME_ACTIVE_WEEKENDS_MAX,
    WEIGHT_COVERAGE_SHORTFALL,
    WEIGHT_DEFICIT_VARIANCE,
    WEIGHT_HOUR_DEFICIT,
    WEIGHT_HOUR_DEFICIT_FULLTIME,
    WEIGHT_HOUR_DEVIATION,
    WEIGHT_N_TO_D_FATIGUE,
    WEIGHT_UNFILLED_ESCALATED,
    WEIGHT_WEEKDAY_SURPLUS_SMOOTH,
    WEIGHT_WEEKEND_BASELINE_SURPLUS,
    band_to_shift_code,
    build_alternate_shift_distribution_rows,
    compute_employee_alternate_shift_share,
    compute_shift_equity_metrics,
    compute_pool_equity_for_all_employees,
    format_shift_equity_metrics_summary,
    alternate_shift_rows_from_equity_metrics,
    is_vacant_portage_line,
    shift_code_to_band,
    solve_vacant_unassigned_slots,
)

__all__ = [
    "CpSatFillResult",
    "PORTAGE_MAX_CONSECUTIVE_NIGHTS",
    "PORTAGE_MAX_CONSECUTIVE_WORK_DAYS",
    "FULLTIME_ACTIVE_WEEKENDS_REQUIRED",
    "PARTTIME_ACTIVE_WEEKENDS_MAX",
    "WEIGHT_COVERAGE_SHORTFALL",
    "WEIGHT_DEFICIT_VARIANCE",
    "WEIGHT_HOUR_DEFICIT",
    "WEIGHT_HOUR_DEFICIT_FULLTIME",
    "WEIGHT_HOUR_DEVIATION",
    "WEIGHT_N_TO_D_FATIGUE",
    "WEIGHT_UNFILLED_ESCALATED",
    "WEIGHT_WEEKDAY_SURPLUS_SMOOTH",
    "WEIGHT_WEEKEND_BASELINE_SURPLUS",
    "band_to_shift_code",
    "build_alternate_shift_distribution_rows",
    "compute_employee_alternate_shift_share",
    "compute_shift_equity_metrics",
    "compute_pool_equity_for_all_employees",
    "format_shift_equity_metrics_summary",
    "alternate_shift_rows_from_equity_metrics",
    "is_vacant_portage_line",
    "shift_code_to_band",
    "solve_vacant_unassigned_slots",
]
